export const dummyThoughts = [
  // Tasks
  { thought_text: "Schedule dentist appointment for next week", type: "task", importance: "medium", category: "Health", sentiment: "neutral", deadline: "2025-10-12", time_needed_minutes: 15 },
  { thought_text: "Finish quarterly report by Friday", type: "task", importance: "high", category: "Work", sentiment: "stressed", deadline: "2025-10-10", time_needed_minutes: 180 },
  { thought_text: "Buy groceries - milk, eggs, bread, vegetables", type: "task", importance: "medium", category: "Personal", sentiment: "neutral", deadline: "2025-10-06", time_needed_minutes: 45 },
  { thought_text: "Call mom to wish her happy birthday", type: "task", importance: "high", category: "Family", sentiment: "positive", deadline: "2025-10-08", time_needed_minutes: 30 },
  { thought_text: "Renew car insurance before it expires", type: "task", importance: "high", category: "Finance", sentiment: "neutral", deadline: "2025-10-15", time_needed_minutes: 60 },
  { thought_text: "Fix the leaky faucet in the bathroom", type: "task", importance: "medium", category: "Home", sentiment: "neutral", deadline: "2025-10-20", time_needed_minutes: 90 },
  { thought_text: "Submit expense reports from last month", type: "task", importance: "medium", category: "Work", sentiment: "neutral", deadline: "2025-10-11", time_needed_minutes: 45 },
  { thought_text: "Pick up dry cleaning", type: "task", importance: "low", category: "Personal", sentiment: "neutral", deadline: "2025-10-07", time_needed_minutes: 20 },
  { thought_text: "Update resume with recent projects", type: "task", importance: "medium", category: "Career", sentiment: "motivated", deadline: "2025-10-18", time_needed_minutes: 120 },
  { thought_text: "Book flight for holiday trip", type: "task", importance: "high", category: "Travel", sentiment: "excited", deadline: "2025-10-09", time_needed_minutes: 60 },
  { thought_text: "Organize the garage this weekend", type: "task", importance: "low", category: "Home", sentiment: "neutral", deadline: "2025-10-13", time_needed_minutes: 240 },
  { thought_text: "Review and sign the contract", type: "task", importance: "high", category: "Work", sentiment: "focused", deadline: "2025-10-08", time_needed_minutes: 45 },
  { thought_text: "Water the plants", type: "task", importance: "low", category: "Home", sentiment: "neutral", deadline: "2025-10-06", time_needed_minutes: 10 },
  { thought_text: "Prepare presentation for client meeting", type: "task", importance: "high", category: "Work", sentiment: "anxious", deadline: "2025-10-16", time_needed_minutes: 180 },
  { thought_text: "Pay utility bills", type: "task", importance: "high", category: "Finance", sentiment: "neutral", deadline: "2025-10-10", time_needed_minutes: 30 },

  // Ideas
  { thought_text: "Start a podcast about mental wellness and productivity", type: "idea", importance: "medium", category: "Career", sentiment: "excited", deadline: null, time_needed_minutes: null },
  { thought_text: "Create a morning routine that includes meditation and journaling", type: "idea", importance: "medium", category: "Personal", sentiment: "hopeful", deadline: null, time_needed_minutes: null },
  { thought_text: "Build a small vegetable garden in the backyard", type: "idea", importance: "low", category: "Home", sentiment: "positive", deadline: null, time_needed_minutes: null },
  { thought_text: "Learn to play the guitar", type: "idea", importance: "low", category: "Hobbies", sentiment: "curious", deadline: null, time_needed_minutes: null },
  { thought_text: "Write a book about my experiences traveling", type: "idea", importance: "medium", category: "Creative", sentiment: "inspired", deadline: null, time_needed_minutes: null },
  { thought_text: "Develop an app to help people track their daily habits", type: "idea", importance: "high", category: "Career", sentiment: "motivated", deadline: null, time_needed_minutes: null },
  { thought_text: "Start a YouTube channel about cooking simple meals", type: "idea", importance: "low", category: "Hobbies", sentiment: "excited", deadline: null, time_needed_minutes: null },
  { thought_text: "Organize a monthly game night with friends", type: "idea", importance: "medium", category: "Social", sentiment: "positive", deadline: null, time_needed_minutes: null },
  { thought_text: "Take an online course on data science", type: "idea", importance: "medium", category: "Learning", sentiment: "curious", deadline: null, time_needed_minutes: null },
  { thought_text: "Volunteer at the local animal shelter", type: "idea", importance: "medium", category: "Community", sentiment: "compassionate", deadline: null, time_needed_minutes: null },
  { thought_text: "Create a budget tracking system", type: "idea", importance: "high", category: "Finance", sentiment: "practical", deadline: null, time_needed_minutes: null },
  { thought_text: "Plan a surprise party for best friend", type: "idea", importance: "medium", category: "Social", sentiment: "excited", deadline: null, time_needed_minutes: null },

  // Reminders
  { thought_text: "Remember to take vitamins daily", type: "reminder", importance: "medium", category: "Health", sentiment: "neutral", deadline: null, time_needed_minutes: 2 },
  { thought_text: "Follow up with Sarah about the project proposal", type: "reminder", importance: "high", category: "Work", sentiment: "focused", deadline: "2025-10-07", time_needed_minutes: 15 },
  { thought_text: "Backup computer files every week", type: "reminder", importance: "medium", category: "Personal", sentiment: "neutral", deadline: null, time_needed_minutes: 30 },
  { thought_text: "Check tire pressure before road trip", type: "reminder", importance: "high", category: "Travel", sentiment: "cautious", deadline: "2025-10-14", time_needed_minutes: 15 },
  { thought_text: "Send thank you card to Aunt Linda", type: "reminder", importance: "medium", category: "Family", sentiment: "grateful", deadline: "2025-10-09", time_needed_minutes: 20 },
  { thought_text: "Replace air filters in HVAC system", type: "reminder", importance: "medium", category: "Home", sentiment: "neutral", deadline: "2025-10-25", time_needed_minutes: 30 },
  { thought_text: "Check expiration dates on pantry items", type: "reminder", importance: "low", category: "Home", sentiment: "neutral", deadline: "2025-10-15", time_needed_minutes: 20 },
  { thought_text: "Update passwords for online accounts", type: "reminder", importance: "high", category: "Security", sentiment: "cautious", deadline: "2025-10-12", time_needed_minutes: 45 },
  { thought_text: "Schedule annual physical exam", type: "reminder", importance: "high", category: "Health", sentiment: "responsible", deadline: "2025-10-20", time_needed_minutes: 15 },
  { thought_text: "Return library books", type: "reminder", importance: "medium", category: "Personal", sentiment: "neutral", deadline: "2025-10-11", time_needed_minutes: 20 },

  // Reflections
  { thought_text: "Feeling grateful for the support from my team during this challenging project", type: "reflection", importance: "medium", category: "Work", sentiment: "grateful", deadline: null, time_needed_minutes: null },
  { thought_text: "I've been neglecting self-care lately. Need to prioritize my mental health", type: "reflection", importance: "high", category: "Personal", sentiment: "concerned", deadline: null, time_needed_minutes: null },
  { thought_text: "The conversation with dad today made me realize how much I've grown", type: "reflection", importance: "medium", category: "Family", sentiment: "reflective", deadline: null, time_needed_minutes: null },
  { thought_text: "I'm proud of how I handled that difficult situation at work", type: "reflection", importance: "medium", category: "Work", sentiment: "proud", deadline: null, time_needed_minutes: null },
  { thought_text: "Need to work on being more present instead of constantly checking my phone", type: "reflection", importance: "high", category: "Personal", sentiment: "mindful", deadline: null, time_needed_minutes: null },
  { thought_text: "The meditation practice is really helping me stay calm throughout the day", type: "reflection", importance: "medium", category: "Health", sentiment: "peaceful", deadline: null, time_needed_minutes: null },
  { thought_text: "I should reach out to old friends more often. Relationships need nurturing", type: "reflection", importance: "medium", category: "Social", sentiment: "thoughtful", deadline: null, time_needed_minutes: null },
  { thought_text: "Realizing that perfectionism is holding me back from taking risks", type: "reflection", importance: "high", category: "Personal", sentiment: "introspective", deadline: null, time_needed_minutes: null },
  { thought_text: "The sunset walk today reminded me to appreciate the simple moments", type: "reflection", importance: "low", category: "Personal", sentiment: "peaceful", deadline: null, time_needed_minutes: null },
  { thought_text: "I've been comparing myself to others too much. Need to focus on my own journey", type: "reflection", importance: "high", category: "Personal", sentiment: "self-aware", deadline: null, time_needed_minutes: null },
  { thought_text: "Grateful for the opportunity to work remotely and have more flexibility", type: "reflection", importance: "medium", category: "Work", sentiment: "grateful", deadline: null, time_needed_minutes: null },
  { thought_text: "Learning to say no has been empowering. I don't have to please everyone", type: "reflection", importance: "high", category: "Personal", sentiment: "empowered", deadline: null, time_needed_minutes: null },

  // Questions
  { thought_text: "What career path would make me truly fulfilled?", type: "question", importance: "high", category: "Career", sentiment: "contemplative", deadline: null, time_needed_minutes: null },
  { thought_text: "How can I be more productive without burning out?", type: "question", importance: "high", category: "Work", sentiment: "curious", deadline: null, time_needed_minutes: null },
  { thought_text: "Should I invest in stocks or real estate?", type: "question", importance: "medium", category: "Finance", sentiment: "uncertain", deadline: null, time_needed_minutes: null },
  { thought_text: "What's the best way to learn a new language efficiently?", type: "question", importance: "medium", category: "Learning", sentiment: "curious", deadline: null, time_needed_minutes: null },
  { thought_text: "How do I maintain work-life balance?", type: "question", importance: "high", category: "Personal", sentiment: "stressed", deadline: null, time_needed_minutes: null },
  { thought_text: "What exercises are best for improving flexibility?", type: "question", importance: "low", category: "Health", sentiment: "curious", deadline: null, time_needed_minutes: null },
  { thought_text: "Should I move to a different city for better opportunities?", type: "question", importance: "high", category: "Career", sentiment: "uncertain", deadline: null, time_needed_minutes: null },
  { thought_text: "How can I improve my public speaking skills?", type: "question", importance: "medium", category: "Career", sentiment: "motivated", deadline: null, time_needed_minutes: null },
  { thought_text: "What's the most effective way to save for retirement?", type: "question", importance: "high", category: "Finance", sentiment: "practical", deadline: null, time_needed_minutes: null },
  { thought_text: "How do I build better habits that stick?", type: "question", importance: "high", category: "Personal", sentiment: "curious", deadline: null, time_needed_minutes: null },

  // Events
  { thought_text: "Team building event at the office", type: "event", importance: "medium", category: "Work", sentiment: "positive", deadline: "2025-10-17", time_needed_minutes: 180 },
  { thought_text: "Coffee meeting with potential client", type: "event", importance: "high", category: "Work", sentiment: "focused", deadline: "2025-10-09", time_needed_minutes: 60 },
  { thought_text: "Yoga class at the community center", type: "event", importance: "medium", category: "Health", sentiment: "peaceful", deadline: "2025-10-08", time_needed_minutes: 60 },
  { thought_text: "Dinner with college friends", type: "event", importance: "medium", category: "Social", sentiment: "excited", deadline: "2025-10-12", time_needed_minutes: 120 },
  { thought_text: "Book club meeting to discuss latest novel", type: "event", importance: "low", category: "Hobbies", sentiment: "curious", deadline: "2025-10-19", time_needed_minutes: 90 },
  { thought_text: "Parent-teacher conference at school", type: "event", importance: "high", category: "Family", sentiment: "responsible", deadline: "2025-10-14", time_needed_minutes: 45 },
  { thought_text: "Annual company retreat", type: "event", importance: "high", category: "Work", sentiment: "excited", deadline: "2025-10-22", time_needed_minutes: 480 },
  { thought_text: "Dentist appointment", type: "event", importance: "medium", category: "Health", sentiment: "neutral", deadline: "2025-10-16", time_needed_minutes: 60 },
  { thought_text: "Birthday party for nephew", type: "event", importance: "high", category: "Family", sentiment: "joyful", deadline: "2025-10-13", time_needed_minutes: 180 },
  { thought_text: "Webinar on digital marketing trends", type: "event", importance: "medium", category: "Learning", sentiment: "curious", deadline: "2025-10-11", time_needed_minutes: 90 },
  { thought_text: "Concert at the local theater", type: "event", importance: "medium", category: "Entertainment", sentiment: "excited", deadline: "2025-10-21", time_needed_minutes: 150 },
  { thought_text: "Volunteer day at food bank", type: "event", importance: "medium", category: "Community", sentiment: "compassionate", deadline: "2025-10-18", time_needed_minutes: 240 },

  // More varied thoughts
  { thought_text: "Research best CRM software for small business", type: "task", importance: "high", category: "Work", sentiment: "focused", deadline: "2025-10-10", time_needed_minutes: 120 },
  { thought_text: "Maybe I should try intermittent fasting", type: "idea", importance: "medium", category: "Health", sentiment: "curious", deadline: null, time_needed_minutes: null },
  { thought_text: "Check if passport needs renewal", type: "reminder", importance: "high", category: "Travel", sentiment: "practical", deadline: "2025-10-08", time_needed_minutes: 10 },
  { thought_text: "Today's walk in nature really cleared my mind", type: "reflection", importance: "low", category: "Personal", sentiment: "peaceful", deadline: null, time_needed_minutes: null },
  { thought_text: "What's the difference between IRA and 401k?", type: "question", importance: "high", category: "Finance", sentiment: "curious", deadline: null, time_needed_minutes: null },
  { thought_text: "Networking event at tech hub", type: "event", importance: "high", category: "Career", sentiment: "motivated", deadline: "2025-10-24", time_needed_minutes: 120 },
  { thought_text: "Clean out email inbox and unsubscribe from newsletters", type: "task", importance: "low", category: "Personal", sentiment: "neutral", deadline: "2025-10-15", time_needed_minutes: 60 },
  { thought_text: "Start a side project building a mobile app", type: "idea", importance: "high", category: "Career", sentiment: "inspired", deadline: null, time_needed_minutes: null },
  { thought_text: "Charge the camera batteries before the trip", type: "reminder", importance: "medium", category: "Travel", sentiment: "practical", deadline: "2025-10-13", time_needed_minutes: 5 },
  { thought_text: "I've been spending too much time on social media", type: "reflection", importance: "medium", category: "Personal", sentiment: "concerned", deadline: null, time_needed_minutes: null },
  { thought_text: "How do I negotiate a salary raise effectively?", type: "question", importance: "high", category: "Career", sentiment: "anxious", deadline: null, time_needed_minutes: null },
  { thought_text: "Doctor's appointment for annual checkup", type: "event", importance: "high", category: "Health", sentiment: "responsible", deadline: "2025-10-23", time_needed_minutes: 90 },
  { thought_text: "Review investment portfolio quarterly", type: "task", importance: "high", category: "Finance", sentiment: "focused", deadline: "2025-10-28", time_needed_minutes: 90 },
  { thought_text: "Design a better home office setup for productivity", type: "idea", importance: "medium", category: "Home", sentiment: "creative", deadline: null, time_needed_minutes: null },
  { thought_text: "Download important files before cloud storage expires", type: "reminder", importance: "high", category: "Personal", sentiment: "urgent", deadline: "2025-10-07", time_needed_minutes: 45 },
  { thought_text: "Feeling more confident after completing that challenging project", type: "reflection", importance: "medium", category: "Work", sentiment: "proud", deadline: null, time_needed_minutes: null },
  { thought_text: "What are the pros and cons of working freelance vs full-time?", type: "question", importance: "high", category: "Career", sentiment: "contemplative", deadline: null, time_needed_minutes: null },
  { thought_text: "Wine tasting event with partner", type: "event", importance: "low", category: "Social", sentiment: "excited", deadline: "2025-10-26", time_needed_minutes: 180 },
  { thought_text: "Practice piano for 30 minutes daily", type: "task", importance: "medium", category: "Hobbies", sentiment: "motivated", deadline: null, time_needed_minutes: 30 },
  { thought_text: "Create a capsule wardrobe to simplify daily decisions", type: "idea", importance: "low", category: "Personal", sentiment: "practical", deadline: null, time_needed_minutes: null },
  { thought_text: "Bring reusable bags for grocery shopping", type: "reminder", importance: "low", category: "Personal", sentiment: "responsible", deadline: "2025-10-06", time_needed_minutes: 2 },
  { thought_text: "I need to be more patient with myself during the learning process", type: "reflection", importance: "high", category: "Personal", sentiment: "self-compassionate", deadline: null, time_needed_minutes: null },
  { thought_text: "Which streaming services are actually worth keeping?", type: "question", importance: "low", category: "Finance", sentiment: "practical", deadline: null, time_needed_minutes: null },
  { thought_text: "Photography workshop downtown", type: "event", importance: "medium", category: "Hobbies", sentiment: "excited", deadline: "2025-10-27", time_needed_minutes: 240 },
  { thought_text: "Deep clean the kitchen this Sunday", type: "task", importance: "medium", category: "Home", sentiment: "neutral", deadline: "2025-10-13", time_needed_minutes: 120 },
  { thought_text: "Start a gratitude journal", type: "idea", importance: "high", category: "Personal", sentiment: "hopeful", deadline: null, time_needed_minutes: null },
  { thought_text: "Test smoke detectors monthly", type: "reminder", importance: "high", category: "Home", sentiment: "cautious", deadline: null, time_needed_minutes: 15 },
  { thought_text: "The therapy sessions are helping me process past trauma", type: "reflection", importance: "high", category: "Health", sentiment: "healing", deadline: null, time_needed_minutes: null },
  { thought_text: "What's the best approach to handle conflict at work?", type: "question", importance: "high", category: "Work", sentiment: "stressed", deadline: null, time_needed_minutes: null },
  { thought_text: "Brunch with family", type: "event", importance: "medium", category: "Family", sentiment: "joyful", deadline: "2025-10-20", time_needed_minutes: 120 },

  // More specific thoughts with names for better demo
  { thought_text: "Call John from accounting about the budget discrepancy", type: "task", importance: "high", category: "Work", sentiment: "focused", deadline: "2025-10-08", time_needed_minutes: 20 },
  { thought_text: "Email Sarah the project timeline for Q4", type: "task", importance: "high", category: "Work", sentiment: "focused", deadline: "2025-10-07", time_needed_minutes: 30 },
  { thought_text: "Meet with Dr. Martinez to discuss test results", type: "event", importance: "high", category: "Health", sentiment: "anxious", deadline: "2025-10-15", time_needed_minutes: 45 },
  { thought_text: "Text Mike about weekend plans", type: "reminder", importance: "medium", category: "Social", sentiment: "excited", deadline: "2025-10-06", time_needed_minutes: 5 },
  { thought_text: "Send birthday gift to Lisa - she mentioned wanting that cookbook", type: "task", importance: "high", category: "Family", sentiment: "thoughtful", deadline: "2025-10-10", time_needed_minutes: 60 },
  { thought_text: "Follow up with Jennifer from HR about the promotion discussion", type: "task", importance: "high", category: "Career", sentiment: "hopeful", deadline: "2025-10-11", time_needed_minutes: 30 },
  { thought_text: "Schedule lunch with David to discuss the startup idea", type: "task", importance: "high", category: "Career", sentiment: "excited", deadline: "2025-10-14", time_needed_minutes: 90 },
  { thought_text: "Call the plumber about the water heater - reference number #4521", type: "task", importance: "high", category: "Home", sentiment: "frustrated", deadline: "2025-10-07", time_needed_minutes: 20 },
  { thought_text: "Prepare slides for the pitch to TechCorp - they want to see ROI data", type: "task", importance: "high", category: "Work", sentiment: "determined", deadline: "2025-10-12", time_needed_minutes: 240 },
  { thought_text: "Book table at Olive Garden for anniversary dinner with Alex", type: "task", importance: "high", category: "Personal", sentiment: "loving", deadline: "2025-10-09", time_needed_minutes: 15 },
  { thought_text: "The conversation with Rachel yesterday made me realize I need to set better boundaries at work", type: "reflection", importance: "high", category: "Work", sentiment: "introspective", deadline: null, time_needed_minutes: null },
  { thought_text: "Meeting with Kevin went really well - he seems interested in partnering on the project", type: "reflection", importance: "medium", category: "Work", sentiment: "optimistic", deadline: null, time_needed_minutes: null },
  { thought_text: "Mom's been calling more often lately - I should visit her this month", type: "reflection", importance: "high", category: "Family", sentiment: "concerned", deadline: null, time_needed_minutes: null },
  { thought_text: "Tom's feedback on my presentation was harsh but fair. Need to work on my delivery", type: "reflection", importance: "medium", category: "Work", sentiment: "reflective", deadline: null, time_needed_minutes: null },
  { thought_text: "Coffee chat with Emma about transitioning to product management", type: "event", importance: "medium", category: "Career", sentiment: "curious", deadline: "2025-10-16", time_needed_minutes: 60 },
]
